name: playground
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  build_runner: any
  pedantic: ^1.10.0
  
dependencies: 

  bip39: ^1.0.6
  ed25519_hd_key: ^2.1.0
  hex: ^0.2.0
  http: ^0.13.3
  web3dart: ^2.1.4
  path_provider: ^2.0.2
  web_socket_channel: ^2.1.0
